name: 'install-Require'
description: 'Action to setup installation tools and install R dependencies'
author: 'Ceres Barros'
inputs:
  GitTag:
    description: "A character indicating the branch, commit SHA or tag to append to 'PredictiveEcology/Require@'. Defaults to 'master' branch"
    required: true
    default: "master"
runs:
  using: "composite"
  steps:
      - name: Install remotes
        run: |
          ## Installing pak
          cat("::group::Installing remotes\n")
          cat("::set-output name=os-version::", sessionInfo()$running, "\n", sep = "")
          cat("::set-output name=r-version::", if (grepl("development", rv <- R.Version()$version.string)) as.character(getRversion()) else rv, "\n", sep = "")
          install.packages("remotes")
          cat("::endgroup::\n")
        shell: Rscript {0}

      - name: Install Require
        run: |
          ## Installing/Updating packages
          cat("::group::Installing/updating Require\n")
          RequirePath <- paste0("PredictiveEcology/Require@", "${{ inputs.GitTag }}")
          remotes::install_github(RequirePath)
          cat("::endgroup::\n")
        shell: Rscript {0}
        working-directory: ${{ inputs.working-directory }}
