name: 'install-Rmd-pkgs'
description: 'Action to install packages necessary to render LandR module manuals (.Rmds)'
author: 'Ceres Barros'
inputs:
  upgrade:
    description: "A boolean passed to 'Require::Require(..., upgrade)'"
    required: true
    default: TRUE
runs:
  using: "composite"
  steps:
      - name: Install packages to render module Rmds
        run: |
          cat("::group::Installing bookdown, markdown, knit \n")
          options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/focal/latest", CRAN = "https://cran.rstudio.com"))
          Require::Require(c("bookdown", "rmarkdown", "knitr"),
                           require = FALSE, upgrade = as.logical("${{ inputs.upgrade }}"))
          cat("::endgroup::\n")
          cat("::group::Installing other LandR manual dependencies\n")
          Require::Require(c("git2r", "kableExtra", "openxlsx", "pander"),
                           require = FALSE, upgrade = as.logical("${{ inputs.upgrade }}"))
          Require::Require(c("PredictiveEcology/SpaDES.docs@development"),
                           require = FALSE, upgrade = as.logical("${{ inputs.upgrade }}"))
          cat("::endgroup::\n")
        shell: Rscript {0}
